version: "3.7"
services:
  product-database:
    image: mysql:8.0
    ports:
      - 3434:3306 #uncomment this line if you want to access the database from host machine (PORT 3434 will be available on your host machine)
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: product
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - gue

  auth-database:
    image: mysql:8.0
    ports:
      - 3435:3306 #uncomment this line if you want to access the database from host machine (PORT 3435 will be available on your host machine)
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: auth
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - gue

  order-database:
    image: mysql:8.0
    ports:
      - 3436:3306 #uncomment this line if you want to access the database from host machine (PORT 3436 will be available on your host machine)
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: order
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - gue

  product:
    image: product
    build: ./product
    depends_on:
      product-database:
        condition: service_healthy
    networks:
      - gue
    ports:
      - 3002:3002 #uncomment this line if you want to access the product service from host machine (PORT 3002 will be available on your host machine)

  auth:
    image: auth
    build: ./auth
    depends_on:
      auth-database:
        condition: service_healthy
    networks:
      - gue
    ports:
      - 3001:3001 #uncomment this line if you want to access the auth service from host machine (PORT 3001 will be available on your host machine)

  order:
    image: order
    build: ./order
    depends_on:
      order-database:
        condition: service_healthy
    networks:
      - gue
    ports:
      - 3003:3003 #uncomment this line if you want to access the auth service from host machine (PORT 3003 will be available on your host machine)

  api-gateway:
    image: nginx:alpine
    ports:
      - 8878:80 # Change 8878 to any port you want to access the gateway from host machine
    depends_on:
      - product
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - gue

networks:
  gue:
